### ISSUE TITLE
FastTreeMP: FastTree.c:3342: ReadTree: Assertion `new < maxnodes' failed.

### ISSUE THREAD

**Issue by brmagalis** [tsibley/FastTree#1]
Hi!

I am new to this error - I have used the following parameters before for similar trees, but aI lost as to the why the error (in the subject line) is being produced:
[uncondensed-final-tree.nh.tree.zip](https://github.com/vinuesa/get_phylomarkers/files/6679431/uncondensed-final-tree.nh.tree.zip)

FastTreeMP -nt -gamma -nni 0 -spr 2 -sprlength 1000 -boot 100 -log fasttree.log -intree uncondensed-final-tree.nh.tree clean.aln > reop.tree

Thanks for your help in advance. I believe the alignment is over the 25 MB limit for github, so please let me know how you would like me to share this with you.
[uncondensed-final-tree.nh.tree.zip](https://github.com/tsibley/FastTree/files/6679436/uncondensed-final-tree.nh.tree.zip)

**Comment by tsibley** [comment]
Hi @brmagalis. Sorry to hear you're having trouble with FastTree. Unfortunately, I'm not able to offer support for it. I created this repository to make it easier for me to build FastTree binaries, but I'm not FastTree's author. You might be able to find help from FastTree's authors, listed on its homepage: http://www.microbesonline.org/fasttree/#Contact

**Comment by brmagalis** [comment]
﻿It's ok, I figured out the issue. Thank you for getting back to me; I just quickly searched through github and did not notice that you were not on the list of authors. I will email them from now on with any issues.

 

Thanks!

 

From: Thomas Sibley ***@***.***>
Reply-To: tsibley/FastTree ***@***.***>
Date: Tuesday, June 22, 2021 at 11:59 AM
To: tsibley/FastTree ***@***.***>
Cc: Brittany Rife Magalis ***@***.***>, Mention ***@***.***>
Subject: Re: [tsibley/FastTree] FastTreeMP: FastTree.c:3342: ReadTree: Assertion `new < maxnodes' failed. (#1)

 

Hi @brmagalis. Sorry to hear you're having trouble with FastTree. Unfortunately, I'm not able to offer support for it. I created this repository to make it easier for me to build FastTree binaries, but I'm not FastTree's author. You might be able to find help from FastTree's authors, listed on its homepage: http://www.microbesonline.org/fasttree/#Contact
